# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: false

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          pm2 stop 0
          touch .env
          echo -e "DATABASE_URI=${{secrets.DATABASE_URI}}\nNODE_ENV=${{secrets.NODE_ENV}}\nACCESS_TOKEN_KEY=${{secrets.ACCESS_TOKEN_KEY}}\nREFRESH_TOKEN_KEY=${{secrets.REFRESH_TOKEN_KEY}}" >> .env
          cat .env
          ncu -u
          npm install
          cd frontend-app
          ncu -u
          npm install
          npm run build
          cd ..
          sudo service nginx restart
          pm2 start 0
          pm2 save
